### ISSUE TITLE
demo todo

### ISSUE THREAD

**Issue by sayanee** [sayanee/iot-security-lecture#1]
- [x] combine http and https servers in one node.js script
- [x] run `avahi-daemon` in raspberry pi and give the 2 server a fixed domain name `lamp.local`
- [x] [regenerate certificate](http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/) based on the `https` domain name
- [x] fix `nmap` issue in laptop
  - `nmap --open -p 22 192.168.0.0-255`
  - connect to router `192.168.0.254` and see the DHCP Client list
- [x] run both servers on raspberry pi bootup
