### ISSUE TITLE
demo todo

### ISSUE THREAD

**Issue by sayanee** [sayanee/iot-security-lecture#5]
-  [x] `oven.local` enable `tshark` command on bootup 
- [ ] pipe to a `tshark.log` files
- [x] infinite while loop that will keep turning off the lamp in `lamp.local`
